### ISSUE TITLE
Error while setting up the project

### ISSUE THREAD

**Issue by kanav1603** [MobinaJafarian/DeluxeRealProperty#1]
I have followed each and every steps mentioned in the `setup` section, i have also installed dependencies by running command `composer install`  then as mentioned I executed `php -S localhost:8000 -t public` command but 

![image](https://user-images.githubusercontent.com/109732798/224572904-2b7c2b9e-1e67-4379-8385-03f3b23e884f.png)

What is going wrong?

**Comment by MobinaJafarian** [comment]
Hi 
This error will be solved by using **PHP Version 7.4** 
I will try to fix it to the latest version as soon as possible.
Thanks for reporting the issue
